version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: music-teachers-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: musicteachers_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development app (runs with npm run dev)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: music-teachers-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres-dev:5432/musicteachers_dev?schema=public
      - NEXTAUTH_SECRET=dev-secret-key-not-for-production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres-dev:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_dev_data: